ices/62529-09.rs: fixed with errors
=== stdout ===
=== stderr ===
error[E0599]: the method `accept` exists for struct `FilterConsumer<[closure@/home/runner/work/glacier/glacier/ices/62529-09.rs:40:19: 40:89], _, String>`, but its trait bounds were not satisfied
  --> /home/runner/work/glacier/glacier/ices/62529-09.rs:44:14
   |
26 | struct FilterConsumer<F,T,C> {
   | ----------------------------
   | |
   | method `accept` not found for this
   | doesn't satisfy `_: Consumer<_>`
...
40 |         function: |x:<Str as TypeWithLifetime>::Type| x.chars().all(char::is_alphabetic),
   |                   ----------------------------------------------------------------------
   |                   |
   |                   doesn't satisfy `<_ as FnOnce<(<_ as TypeWithLifetime<'_>>::Type,)>>::Output = bool`
   |                   doesn't satisfy `_: Fn<(<_ as TypeWithLifetime<'_>>::Type,)>`
...
44 |     consumer.accept("hi");
   |              ^^^^^^ method cannot be called on `FilterConsumer<[closure@/home/runner/work/glacier/glacier/ices/62529-09.rs:40:19: 40:89], _, String>` due to unsatisfied trait bounds
   |
   = note: the following trait bounds were not satisfied:
           `<[closure@/home/runner/work/glacier/glacier/ices/62529-09.rs:40:19: 40:89] as FnOnce<(<_ as TypeWithLifetime<'_>>::Type,)>>::Output = bool`
           which is required by `FilterConsumer<[closure@/home/runner/work/glacier/glacier/ices/62529-09.rs:40:19: 40:89], _, String>: Consumer<_>`
           `[closure@/home/runner/work/glacier/glacier/ices/62529-09.rs:40:19: 40:89]: Fn<(<_ as TypeWithLifetime<'_>>::Type,)>`
           which is required by `FilterConsumer<[closure@/home/runner/work/glacier/glacier/ices/62529-09.rs:40:19: 40:89], _, String>: Consumer<_>`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
==============