ices/83641.sh: fixed with errors (#737)
=== stdout ===
=== stderr ===
error: can't qualify macro_rules invocation with `pub`
 --> <anon>:2:1
  |
2 | pub macro_rules! fail {
  | ^^^ help: try exporting the macro: `#[macro_export]`

error[E0557]: feature has been removed
 --> <anon>:1:12
  |
1 | #![feature(pub_macro_rules)]
  |            ^^^^^^^^^^^^^^^ feature has been removed
  |
  = note: removed due to being incomplete, in particular it does not work across crates

warning: unused macro definition
 --> <anon>:2:1
  |
2 | / pub macro_rules! fail {
3 | |     ($x:expr) => { $x }
4 | | }
  | |_^
  |
  = note: `#[warn(unused_macros)]` on by default

error: aborting due to 2 previous errors; 1 warning emitted

For more information about this error, try `rustc --explain E0557`.
error[E0463]: can't find crate for `repro`
 --> <anon>:1:1
  |
1 | extern crate repro;
  | ^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
==============

Co-authored-by: rustbot <rustbot@users.noreply.github.com>