ices/96525.sh: fixed with errors
=== stdout ===
=== stderr ===
error[E0106]: missing lifetime specifier
 --> <anon>:4:19
  |
4 | async fn foo() -> Struct {
  |                   ^^^^^^ expected named lifetime parameter
  |
  = help: this function's return type contains a borrowed value, but there is no value for it to be borrowed from
help: consider using the `'static` lifetime
  |
4 | async fn foo() -> Struct<'static> {
  |                   ~~~~~~~~~~~~~~~

error: aborting due to previous error

For more information about this error, try `rustc --explain E0106`.
==============