ices/71381.rs: fixed with errors
=== stdout ===
=== stderr ===
error[E0557]: feature has been removed
 --> /home/runner/work/glacier/glacier/ices/71381.rs:1:28
  |
1 | #![feature(const_generics, const_compare_raw_pointers)]
  |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^ feature has been removed
  |
  = note: cannot be allowed in const eval in any meaningful way

error: using function pointers as const generic parameters is forbidden
  --> /home/runner/work/glacier/glacier/ices/71381.rs:13:61
   |
13 |     pub fn call_me<Args: Sized, const IDX: usize, const FN: unsafe extern "C" fn(Args)>(&self) {
   |                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^

error: using function pointers as const generic parameters is forbidden
  --> /home/runner/work/glacier/glacier/ices/71381.rs:20:19
   |
20 |         const FN: unsafe extern "C" fn(Args),
   |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0557`.
==============