ices/77987.rs: fixed with errors
=== stdout ===
=== stderr ===
error[E0557]: feature has been removed
 --> /home/runner/work/glacier/glacier/ices/77987.rs:1:12
  |
1 | #![feature(min_type_alias_impl_trait)]
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^ feature has been removed
  |
  = note: removed in favor of full type_alias_impl_trait

error: aborting due to previous error

For more information about this error, try `rustc --explain E0557`.
==============