ices/109144.rs: fixed with errors
=== stdout ===
=== stderr ===
error[E0459]: `#[link]` attribute requires a `name = "string"` argument
 --> /home/runner/work/glacier/glacier/ices/109144.rs:2:1
  |
2 | #[link(kind = "static", modifiers = "+whole-archive,+bundle")]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `name` argument

error: aborting due to previous error

For more information about this error, try `rustc --explain E0459`.
==============