ices/85350.rs: fixed with errors
=== stdout ===
=== stderr ===
error: lifetime in trait object type must be followed by `+`
 --> /home/runner/work/glacier/glacier/ices/85350.rs:1:26
  |
1 | impl FnMut(&Context) for 'tcx {
  |                          ^^^^

error[E0407]: method `print` is not a member of trait `FnMut`
 --> /home/runner/work/glacier/glacier/ices/85350.rs:2:5
  |
2 |     fn print () -> Self :: Output{ }
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not a member of trait `FnMut`

error[E0412]: cannot find type `Context` in this scope
 --> /home/runner/work/glacier/glacier/ices/85350.rs:1:13
  |
1 | impl FnMut(&Context) for 'tcx {
  |             ^^^^^^^ not found in this scope
  |
help: consider importing one of these items
  |
1 | use core::task::Context;
  |
1 | use std::task::Context;
  |

error[E0601]: `main` function not found in crate `85350`
 --> /home/runner/work/glacier/glacier/ices/85350.rs:3:2
  |
3 | }
  |  ^ consider adding a `main` function to `/home/runner/work/glacier/glacier/ices/85350.rs`

error[E0224]: at least one trait is required for an object type
 --> /home/runner/work/glacier/glacier/ices/85350.rs:1:26
  |
1 | impl FnMut(&Context) for 'tcx {
  |                          ^^^^

error[E0183]: manual implementations of `FnMut` are experimental
 --> /home/runner/work/glacier/glacier/ices/85350.rs:1:6
  |
1 | impl FnMut(&Context) for 'tcx {
  |      ^^^^^^^^^^^^^^^ manual implementations of `FnMut` are experimental
  |
  = help: add `#![feature(unboxed_closures)]` to the crate attributes to enable

error[E0261]: use of undeclared lifetime name `'tcx`
 --> /home/runner/work/glacier/glacier/ices/85350.rs:1:26
  |
1 | impl FnMut(&Context) for 'tcx {
  |     -                    ^^^^ undeclared lifetime
  |     |
  |     help: consider introducing lifetime `'tcx` here: `<'tcx>`

error[E0229]: associated type bindings are not allowed here
 --> /home/runner/work/glacier/glacier/ices/85350.rs:1:6
  |
1 | impl FnMut(&Context) for 'tcx {
  |      ^^^^^^^^^^^^^^^ associated type not allowed here

error: aborting due to 8 previous errors

Some errors have detailed explanations: E0183, E0224, E0229, E0261, E0407, E0412, E0601.
For more information about an error, try `rustc --explain E0183`.
==============