ices/72845.rs: fixed with errors
=== stdout ===
=== stderr ===
error[E0557]: feature has been removed
 --> /home/runner/work/glacier/glacier/ices/72845.rs:1:12
  |
1 | #![feature(const_generics)]
  |            ^^^^^^^^^^^^^^ feature has been removed
  |
  = note: removed in favor of `#![feature(adt_const_params]` and `#![feature(generic_const_exprs)]`

error: generic parameters may not be used in const operations
  --> /home/runner/work/glacier/glacier/ices/72845.rs:27:44
   |
27 | impl<T: Type> Spec1 for T where Predicate<{T::AT::C > 0}>: Satisfied {}
   |                                            ^^^^^^^^ cannot perform const operation using `T`
   |
   = note: type parameters may not be used in const expressions
   = help: use `#![feature(generic_const_exprs)]` to allow generic const expressions

error: generic parameters may not be used in const operations
  --> /home/runner/work/glacier/glacier/ices/72845.rs:31:52
   |
31 | impl<T: Type + Spec1> Spec2 for T where Predicate<{T::AT::C > 1}>: Satisfied {}
   |                                                    ^^^^^^^^ cannot perform const operation using `T`
   |
   = note: type parameters may not be used in const expressions
   = help: use `#![feature(generic_const_exprs)]` to allow generic const expressions

error[E0601]: `main` function not found in crate `72845`
  --> /home/runner/work/glacier/glacier/ices/72845.rs:1:1
   |
1  | / #![feature(const_generics)]
2  | | #![feature(specialization)]
3  | | #![allow(incomplete_features)]
4  | |
...  |
44 | |     fn Bar() {}
45 | | }
   | |_^ consider adding a `main` function to `/home/runner/work/glacier/glacier/ices/72845.rs`

error: aborting due to 4 previous errors

Some errors have detailed explanations: E0557, E0601.
For more information about an error, try `rustc --explain E0557`.
==============