ices/78520.sh: fixed with errors
=== stdout ===
=== stderr ===
error[E0557]: feature has been removed
 --> <anon>:4:12
  |
4 | #![feature(const_generics)]
  |            ^^^^^^^^^^^^^^ feature has been removed
  |
  = note: removed in favor of `#![feature(adt_const_params]` and `#![feature(generic_const_exprs)]`

error: `&'static str` is forbidden as the type of a const generic parameter
 --> <anon>:6:21
  |
6 | struct Bug<const S: &'static str>;
  |                     ^^^^^^^^^^^^
  |
  = note: the only supported types are integers, `bool` and `char`
  = help: more complex types are supported with `#![feature(adt_const_params)]`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0557`.
==============