ices/93955.rs: fixed with errors
=== stdout ===
=== stderr ===
error[E0107]: this function takes 2 generic arguments but 1 generic argument was supplied
  --> /home/runner/work/glacier/glacier/ices/93955.rs:32:13
   |
32 |     let b = add::<i32>(x, y); // ICE
   |             ^^^   --- supplied 1 generic argument
   |             |
   |             expected 2 generic arguments
   |
note: function defined here, with 2 generic parameters: `T`, `U`
  --> /home/runner/work/glacier/glacier/ices/93955.rs:20:4
   |
20 | fn add<T, U>(x: T, y: T) -> T
   |    ^^^ -  -
help: add missing generic argument
   |
32 |     let b = add::<i32, U>(x, y); // ICE
   |                      +++

error: aborting due to previous error

For more information about this error, try `rustc --explain E0107`.
==============