ices/45814.rs: fixed with errors
=== stdout ===
=== stderr ===
warning: the feature `specialization` is incomplete and may not be safe to use and/or cause compiler crashes
 --> /home/runner/work/glacier/glacier/ices/45814.rs:1:12
  |
1 | #![feature(specialization)]
  |            ^^^^^^^^^^^^^^
  |
  = note: `#[warn(incomplete_features)]` on by default
  = note: see issue #31844 <https://github.com/rust-lang/rust/issues/31844> for more information
  = help: consider using `min_specialization` instead, which is more stable and complete

error[E0275]: overflow evaluating the requirement `T: Trait<_>`
  |
  = help: consider increasing the recursion limit by adding a `#![recursion_limit = "256"]` attribute to your crate (`45814`)
note: required because of the requirements on the impl of `Trait<_>` for `T`
 --> /home/runner/work/glacier/glacier/ices/45814.rs:5:20
  |
5 | default impl<T, U> Trait<T> for U { }
  |                    ^^^^^^^^     ^
  = note: 128 redundant requirements hidden
  = note: required because of the requirements on the impl of `Trait<_>` for `T`

error: aborting due to previous error; 1 warning emitted

For more information about this error, try `rustc --explain E0275`.
==============