ices/86033.rs: fixed with errors
=== stdout ===
=== stderr ===
error[E0557]: feature has been removed
 --> /home/runner/work/glacier/glacier/ices/86033.rs:1:12
  |
1 | #![feature(const_generics)]
  |            ^^^^^^^^^^^^^^ feature has been removed
  |
  = note: removed in favor of `#![feature(adt_const_params]` and `#![feature(generic_const_exprs)]`

error[E0557]: feature has been removed
 --> /home/runner/work/glacier/glacier/ices/86033.rs:2:12
  |
2 | #![feature(const_evaluatable_checked)]
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^ feature has been removed
  |
  = note: renamed to `generic_const_exprs`

error: generic parameters may not be used in const operations
  --> /home/runner/work/glacier/glacier/ices/86033.rs:11:38
   |
11 |     (): IsTrue<{ std::mem::size_of::<T>() == 0 }>
   |                                      ^ cannot perform const operation using `T`
   |
   = note: type parameters may not be used in const expressions
   = help: use `#![feature(generic_const_exprs)]` to allow generic const expressions

error[E0601]: `main` function not found in crate `86033`
  --> /home/runner/work/glacier/glacier/ices/86033.rs:1:1
   |
1  | / #![feature(const_generics)]
2  | | #![feature(const_evaluatable_checked)]
3  | |
4  | | pub trait IsTrue<const T: bool> {}
...  |
15 | |     || {}
16 | | }
   | |_^ consider adding a `main` function to `/home/runner/work/glacier/glacier/ices/86033.rs`

error: aborting due to 4 previous errors

Some errors have detailed explanations: E0557, E0601.
For more information about an error, try `rustc --explain E0557`.
==============