ices/71176.rs: fixed with errors
=== stdout ===
=== stderr ===
error[E0107]: missing generics for associated type `Provider::A`
 --> /home/runner/work/glacier/glacier/ices/71176.rs:5:10
  |
5 |     type A<'a>;
  |          ^ expected 1 lifetime argument
  |
note: associated type defined here, with 1 lifetime parameter: `'a`
 --> /home/runner/work/glacier/glacier/ices/71176.rs:5:10
  |
5 |     type A<'a>;
  |          ^ --
help: use angle brackets to add missing lifetime argument
  |
5 |     type A<'a><'a>;
  |           ^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0107`.
==============