ices/86201.rs: fixed with errors
=== stdout ===
=== stderr ===
error[E0557]: feature has been removed
 --> /home/runner/work/glacier/glacier/ices/86201.rs:3:12
  |
3 | #![feature(impl_trait_in_bindings)]
  |            ^^^^^^^^^^^^^^^^^^^^^^ feature has been removed
  |
  = note: the implementation was not maintainable, the feature may get reintroduced once the current refactorings are done

error[E0308]: mismatched types
 --> /home/runner/work/glacier/glacier/ices/86201.rs:6:29
  |
5 | type FunType = impl Fn<()>;
  |                ----------- the expected opaque type
6 | static STATIC_FN: FunType = some_fn;
  |                             ^^^^^^^ expected opaque type, found fn item
  |
  = note: expected opaque type `impl Fn<()>`
                 found fn item `fn() {some_fn}`

error: could not find defining uses
 --> /home/runner/work/glacier/glacier/ices/86201.rs:5:16
  |
5 | type FunType = impl Fn<()>;
  |                ^^^^^^^^^^^

error: aborting due to 3 previous errors

Some errors have detailed explanations: E0308, E0557.
For more information about an error, try `rustc --explain E0308`.
==============