ices/66387.rs: fixed with errors
=== stdout ===
=== stderr ===
error[E0670]: `async fn` is not permitted in the 2015 edition
 --> /home/runner/work/glacier/glacier/ices/66387.rs:1:1
  |
1 | async fn f() -> i32 {
  | ^^^^^

error[E0601]: `main` function not found in crate `66387`
 --> /home/runner/work/glacier/glacier/ices/66387.rs:1:1
  |
1 | / async fn f() -> i32 {
2 | |     if true {
3 | |         return 0;
4 | |     }
5 | | }
  | |_^ consider adding a `main` function to `/home/runner/work/glacier/glacier/ices/66387.rs`

error[E0317]: if may be missing an else clause
 --> /home/runner/work/glacier/glacier/ices/66387.rs:2:5
  |
2 | /     if true {
3 | |         return 0;
4 | |     }
  | |_____^ expected (), found i32
  |
  = note: expected type `()`
             found type `i32`
  = note: `if` expressions without `else` evaluate to `()`
  = help: consider adding an `else` block that evaluates to the expected type

error: aborting due to 3 previous errors

Some errors have detailed explanations: E0317, E0601, E0670.
For more information about an error, try `rustc --explain E0317`.
==============