ices/79674.rs: fixed with errors
=== stdout ===
=== stderr ===
error[E0557]: feature has been removed
 --> /home/runner/work/glacier/glacier/ices/79674.rs:1:12
  |
1 | #![feature(const_evaluatable_checked, const_fn, const_fn_trait_bound, const_generics)]
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^ feature has been removed
  |
  = note: renamed to `generic_const_exprs`

error[E0557]: feature has been removed
 --> /home/runner/work/glacier/glacier/ices/79674.rs:1:39
  |
1 | #![feature(const_evaluatable_checked, const_fn, const_fn_trait_bound, const_generics)]
  |                                       ^^^^^^^^ feature has been removed
  |
  = note: split into finer-grained feature gates

error[E0557]: feature has been removed
 --> /home/runner/work/glacier/glacier/ices/79674.rs:1:71
  |
1 | #![feature(const_evaluatable_checked, const_fn, const_fn_trait_bound, const_generics)]
  |                                                                       ^^^^^^^^^^^^^^ feature has been removed
  |
  = note: removed in favor of `#![feature(adt_const_params]` and `#![feature(generic_const_exprs)]`

error: generic parameters may not be used in const operations
  --> /home/runner/work/glacier/glacier/ices/79674.rs:23:26
   |
23 |     Lift<{is_same_type::<A, B>()}>: IsFalse {}
   |                          ^ cannot perform const operation using `A`
   |
   = note: type parameters may not be used in const expressions
   = help: use `#![feature(generic_const_exprs)]` to allow generic const expressions

error: generic parameters may not be used in const operations
  --> /home/runner/work/glacier/glacier/ices/79674.rs:23:29
   |
23 |     Lift<{is_same_type::<A, B>()}>: IsFalse {}
   |                             ^ cannot perform const operation using `B`
   |
   = note: type parameters may not be used in const expressions
   = help: use `#![feature(generic_const_exprs)]` to allow generic const expressions

error: aborting due to 5 previous errors

For more information about this error, try `rustc --explain E0557`.
==============