ices/58956.rs: fixed with errors
=== stdout ===
=== stderr ===
error[E0557]: feature has been removed
 --> /home/runner/work/glacier/glacier/ices/58956.rs:1:12
  |
1 | #![feature(impl_trait_in_bindings)]
  |            ^^^^^^^^^^^^^^^^^^^^^^ feature has been removed
  |
  = note: the implementation was not maintainable, the feature may get reintroduced once the current refactorings are done

error[E0562]: `impl Trait` not allowed outside of function and method return types
 --> /home/runner/work/glacier/glacier/ices/58956.rs:9:11
  |
9 | const _A: impl Lam = {
  |           ^^^^^^^^

error[E0562]: `impl Trait` not allowed outside of function and method return types
  --> /home/runner/work/glacier/glacier/ices/58956.rs:10:17
   |
10 |     let x: Wrap<impl Lam> = Wrap(B);
   |                 ^^^^^^^^

error: aborting due to 3 previous errors

Some errors have detailed explanations: E0557, E0562.
For more information about an error, try `rustc --explain E0557`.
==============