ices/84659.rs: fixed with errors
=== stdout ===
=== stderr ===
error[E0557]: feature has been removed
 --> /home/runner/work/glacier/glacier/ices/84659.rs:2:12
  |
2 | #![feature(const_generics)]
  |            ^^^^^^^^^^^^^^ feature has been removed
  |
  = note: removed in favor of `#![feature(adt_const_params]` and `#![feature(generic_const_exprs)]`

error: generic parameters may not be used in const operations
 --> /home/runner/work/glacier/glacier/ices/84659.rs:8:21
  |
8 |     type Baz: Bar<{ Self::N }>;
  |                     ^^^^^^^ cannot perform const operation using `Self`
  |
  = note: type parameters may not be used in const expressions
  = help: use `#![feature(generic_const_exprs)]` to allow generic const expressions

error[E0601]: `main` function not found in crate `84659`
 --> /home/runner/work/glacier/glacier/ices/84659.rs:1:1
  |
1 | / #![allow(incomplete_features)]
2 | | #![feature(const_generics)]
3 | |
4 | | trait Bar<const N: usize> {}
... |
8 | |     type Baz: Bar<{ Self::N }>;
9 | | }
  | |_^ consider adding a `main` function to `/home/runner/work/glacier/glacier/ices/84659.rs`

error: aborting due to 3 previous errors

Some errors have detailed explanations: E0557, E0601.
For more information about an error, try `rustc --explain E0557`.
==============