ices/93646.rs: fixed with errors
=== stdout ===
=== stderr ===
error[E0106]: missing lifetime specifier
 --> /home/runner/work/glacier/glacier/ices/93646.rs:2:12
  |
2 |     let s: &str; s.len()
  |            ^ expected named lifetime parameter
  |
help: consider introducing a named lifetime parameter
  |
1 ~ struct X<const 'a, N: usize = {
2 ~     let s: &'a str; s.len()
  |

error: aborting due to previous error

For more information about this error, try `rustc --explain E0106`.
==============