ices/68652.rs: fixed with errors
=== stdout ===
=== stderr ===
warning: the feature `generic_associated_types` is incomplete and may not be safe to use and/or cause compiler crashes
 --> /home/runner/work/glacier/glacier/ices/68652.rs:1:12
  |
1 | #![feature(generic_associated_types)]
  |            ^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(incomplete_features)]` on by default
  = note: see issue #44265 <https://github.com/rust-lang/rust/issues/44265> for more information

error[E0107]: missing generics for associated type `Fun::F`
 --> /home/runner/work/glacier/glacier/ices/68652.rs:4:10
  |
4 |     type F<'a>: ?Sized;
  |          ^ expected 1 lifetime argument
  |
note: associated type defined here, with 1 lifetime parameter: `'a`
 --> /home/runner/work/glacier/glacier/ices/68652.rs:4:10
  |
4 |     type F<'a>: ?Sized;
  |          ^ --
help: use angle brackets to add missing lifetime argument
  |
4 |     type F<'a><'a>: ?Sized;
  |           ^^^^

error: aborting due to previous error; 1 warning emitted

For more information about this error, try `rustc --explain E0107`.
==============