ices/112630.rs: fixed with errors
=== stdout ===
=== stderr ===
error[E0412]: cannot find type `B` in this scope
 --> /home/runner/work/glacier/glacier/ices/112630.rs:2:9
  |
2 |     Bar(B),
  |         ^ not found in this scope
  |
help: you might be missing a type parameter
  |
1 | enum Foo<B> {
  |         +++

error: aborting due to 1 previous error

For more information about this error, try `rustc --explain E0412`.
==============