ices/72352.rs: fixed with errors
=== stdout ===
=== stderr ===
error[E0557]: feature has been removed
 --> /home/runner/work/glacier/glacier/ices/72352.rs:2:12
  |
2 | #![feature(const_compare_raw_pointers)]
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^ feature has been removed
  |
  = note: cannot be allowed in const eval in any meaningful way

error: using function pointers as const generic parameters is forbidden
  --> /home/runner/work/glacier/glacier/ices/72352.rs:15:42
   |
15 | unsafe fn unsafely_do_the_thing<const F: fn(&CStr) -> usize>(ptr: *const i8) -> usize {
   |                                          ^^^^^^^^^^^^^^^^^^

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0557`.
==============