ices/75883.rs: fixed with errors
=== stdout ===
=== stderr ===
error[E0107]: this enum takes 2 type arguments but only 1 type argument was supplied
   --> /home/runner/work/glacier/glacier/ices/75883.rs:4:21
    |
4   |     pub fn run() -> Result<_> {
    |                     ^^^^^^ - supplied 1 type argument
    |                     |
    |                     expected 2 type arguments
    |
note: enum defined here, with 2 type parameters: `T`, `E`
help: add missing type argument
    |
4   |     pub fn run() -> Result<_, E> {
    |                             ^^^

error[E0107]: this enum takes 2 type arguments but only 1 type argument was supplied
   --> /home/runner/work/glacier/glacier/ices/75883.rs:11:35
    |
11  |     pub fn interact(&mut self) -> Result<_> {
    |                                   ^^^^^^ - supplied 1 type argument
    |                                   |
    |                                   expected 2 type arguments
    |
note: enum defined here, with 2 type parameters: `T`, `E`
help: add missing type argument
    |
11  |     pub fn interact(&mut self) -> Result<_, E> {
    |                                           ^^^

error[E0121]: the type placeholder `_` is not allowed within types on item signatures
  --> /home/runner/work/glacier/glacier/ices/75883.rs:11:42
   |
11 |     pub fn interact(&mut self) -> Result<_> {
   |                                          ^ not allowed in type signatures

error[E0121]: the type placeholder `_` is not allowed within types on item signatures
 --> /home/runner/work/glacier/glacier/ices/75883.rs:4:28
  |
4 |     pub fn run() -> Result<_> {
  |                            ^ not allowed in type signatures

error: aborting due to 4 previous errors

Some errors have detailed explanations: E0107, E0121.
For more information about an error, try `rustc --explain E0107`.
==============