ices/92305.sh: fixed with errors
=== stdout ===
=== stderr ===
error[E0107]: missing generics for struct `Vec`
 --> <anon>:4:45
  |
4 | fn f<T>(data: &[T]) -> impl Iterator<Item = Vec> {
  |                                             ^^^ expected at least 1 generic argument
  |
help: add missing generic argument
  |
4 | fn f<T>(data: &[T]) -> impl Iterator<Item = Vec<T>> {
  |                                             ~~~~~~

error[E0282]: type annotations needed
 --> <anon>:5:5
  |
5 |     iter::empty()
  |     ^^^^^^^^^^^ cannot infer type for type parameter `T` declared on the function `empty`

error[E0282]: type annotations needed
 --> <anon>:8:35
  |
8 | fn g<T>(data: &[T], target: T) -> impl Iterator<Item = Vec<T>> {
  |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot infer type

error: aborting due to 3 previous errors

Some errors have detailed explanations: E0107, E0282.
For more information about an error, try `rustc --explain E0107`.
==============