ices/83531.rs: fixed with errors
=== stdout ===
=== stderr ===
error[E0106]: missing lifetime specifier
 --> /home/runner/work/glacier/glacier/ices/83531.rs:3:8
  |
3 |     b: &VTable,
  |        ^ expected named lifetime parameter
  |
help: consider introducing a named lifetime parameter
  |
1 ~ union Foo<'a> {
2 |     a: isize,
3 ~     b: &'a VTable,
  |

error[E0412]: cannot find type `VTable` in this scope
 --> /home/runner/work/glacier/glacier/ices/83531.rs:3:9
  |
3 |     b: &VTable,
  |         ^^^^^^ not found in this scope

error[E0601]: `main` function not found in crate `83531`
 --> /home/runner/work/glacier/glacier/ices/83531.rs:7:2
  |
7 | }
  |  ^ consider adding a `main` function to `/home/runner/work/glacier/glacier/ices/83531.rs`

error: aborting due to 3 previous errors

Some errors have detailed explanations: E0106, E0412, E0601.
For more information about an error, try `rustc --explain E0106`.
==============