ices/72267.sh: fixed with errors
=== stdout ===
=== stderr ===
error: `?Trait` is not permitted in trait object types
 --> 72267.rs:2:17
  |
2 |     let _: Box<(?Sized)>;
  |                 ^^^^^^

warning: trait objects without an explicit `dyn` are deprecated
 --> 72267.rs:2:17
  |
2 |     let _: Box<(?Sized)>;
  |                 ^^^^^^ help: use `dyn`: `dyn ?Sized`
  |
  = note: `#[warn(bare_trait_objects)]` on by default

error[E0224]: at least one trait is required for an object type
 --> 72267.rs:2:17
  |
2 |     let _: Box<(?Sized)>;
  |                 ^^^^^^

error: aborting due to 2 previous errors; 1 warning emitted

For more information about this error, try `rustc --explain E0224`.
==============