ices/79636.rs: fixed with errors
=== stdout ===
=== stderr ===
warning: the feature `generic_associated_types` is incomplete and may not be safe to use and/or cause compiler crashes
 --> /home/runner/work/glacier/glacier/ices/79636.rs:1:12
  |
1 | #![feature(generic_associated_types)]
  |            ^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(incomplete_features)]` on by default
  = note: see issue #44265 <https://github.com/rust-lang/rust/issues/44265> for more information

error[E0107]: missing generics for associated type `Monad::Wrapped`
 --> /home/runner/work/glacier/glacier/ices/79636.rs:5:10
  |
5 |     type Wrapped<B>;
  |          ^^^^^^^ expected 1 type argument
  |
note: associated type defined here, with 1 type parameter: `B`
 --> /home/runner/work/glacier/glacier/ices/79636.rs:5:10
  |
5 |     type Wrapped<B>;
  |          ^^^^^^^ -
help: use angle brackets to add missing type argument
  |
5 |     type Wrapped<B><B>;
  |                 ^^^

error: aborting due to previous error; 1 warning emitted

For more information about this error, try `rustc --explain E0107`.
==============