ices/88997.rs: fixed with errors
=== stdout ===
=== stderr ===
error[E0770]: the type of const parameters must not depend on other generic parameters
 --> /home/runner/work/glacier/glacier/ices/88997.rs:8:40
  |
8 | struct Range<T: PartialOrd, const MIN: T, const MAX: T>(T)
  |                                        ^ the type must not depend on the parameter `T`

error[E0770]: the type of const parameters must not depend on other generic parameters
 --> /home/runner/work/glacier/glacier/ices/88997.rs:8:54
  |
8 | struct Range<T: PartialOrd, const MIN: T, const MAX: T>(T)
  |                                                      ^ the type must not depend on the parameter `T`

error[E0601]: `main` function not found in crate `88997`
  --> /home/runner/work/glacier/glacier/ices/88997.rs:1:1
   |
1  | / #![allow(incomplete_features)]
2  | | #![feature(generic_const_exprs)]
3  | |
4  | | struct ConstAssert<const COND: bool>;
...  |
9  | | where
10 | |     ConstAssert<{ MIN <= MAX }>: True;
   | |______________________________________^ consider adding a `main` function to `/home/runner/work/glacier/glacier/ices/88997.rs`

error: aborting due to 3 previous errors

Some errors have detailed explanations: E0601, E0770.
For more information about an error, try `rustc --explain E0601`.
==============