ices/98372.rs: fixed with errors
=== stdout ===
=== stderr ===
error[E0557]: feature has been removed
 --> /home/runner/work/glacier/glacier/ices/98372.rs:3:5
  |
3 |     untagged_unions, decl_macro, rustc_attrs, transparent_unions, auto_traits,
  |     ^^^^^^^^^^^^^^^ feature has been removed
  |
  = note: unions with `Copy` and `ManuallyDrop` fields are stable; there is no intent to stabilize more

error: aborting due to previous error

For more information about this error, try `rustc --explain E0557`.
==============