ices/85113.rs: fixed with errors
=== stdout ===
=== stderr ===
warning: the feature `impl_trait_in_bindings` is incomplete and may not be safe to use and/or cause compiler crashes
 --> /home/runner/work/glacier/glacier/ices/85113.rs:2:12
  |
2 | #![feature(impl_trait_in_bindings)]
  |            ^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(incomplete_features)]` on by default
  = note: see issue #63065 <https://github.com/rust-lang/rust/issues/63065> for more information

error[E0700]: hidden type for `impl Trait` captures lifetime that does not appear in bounds
 --> /home/runner/work/glacier/glacier/ices/85113.rs:4:29
  |
4 | type OpaqueOutputImpl<'a> = impl Output<'a> + 'a;
  |                             ^^^^^^^^^^^^^^^^^^^^
  |
note: hidden type `&'<empty> str` captures lifetime smaller than the function body
 --> /home/runner/work/glacier/glacier/ices/85113.rs:4:29
  |
4 | type OpaqueOutputImpl<'a> = impl Output<'a> + 'a;
  |                             ^^^^^^^^^^^^^^^^^^^^

error[E0477]: the type `&'<empty> str` does not fulfill the required lifetime
 --> /home/runner/work/glacier/glacier/ices/85113.rs:4:29
  |
4 | type OpaqueOutputImpl<'a> = impl Output<'a> + 'a;
  |                             ^^^^^^^^^^^^^^^^^^^^
  |
note: type must outlive the lifetime `'a` as defined on the item at 4:23
 --> /home/runner/work/glacier/glacier/ices/85113.rs:4:23
  |
4 | type OpaqueOutputImpl<'a> = impl Output<'a> + 'a;
  |                       ^^

error[E0495]: cannot infer an appropriate lifetime for lifetime parameter `'a` due to conflicting requirements
 --> /home/runner/work/glacier/glacier/ices/85113.rs:4:29
  |
4 | type OpaqueOutputImpl<'a> = impl Output<'a> + 'a;
  |                             ^^^^^^^^^^^^^^^^^^^^
  |
  = note: first, the lifetime cannot outlive the empty lifetime...
note: ...but the lifetime must also be valid for the lifetime `'a` as defined on the item at 4:23...
 --> /home/runner/work/glacier/glacier/ices/85113.rs:4:23
  |
4 | type OpaqueOutputImpl<'a> = impl Output<'a> + 'a;
  |                       ^^
note: ...so that the types are compatible
 --> /home/runner/work/glacier/glacier/ices/85113.rs:4:29
  |
4 | type OpaqueOutputImpl<'a> = impl Output<'a> + 'a;
  |                             ^^^^^^^^^^^^^^^^^^^^
  = note: expected `Output<'a>`
             found `Output<'_>`

error: aborting due to 3 previous errors; 1 warning emitted

Some errors have detailed explanations: E0477, E0495, E0700.
For more information about an error, try `rustc --explain E0477`.
==============