ices/83539.rs: fixed with errors
=== stdout ===
=== stderr ===
warning: the feature `rustc_attrs` is internal to the compiler or standard library
 --> /home/runner/work/glacier/glacier/ices/83539.rs:2:12
  |
2 | #![feature(rustc_attrs)]
  |            ^^^^^^^^^^^
  |
  = note: using it is strongly discouraged
  = note: `#[warn(internal_features)]` on by default

error[E0507]: cannot move out of `*x` which is behind a shared reference
 --> /home/runner/work/glacier/glacier/ices/83539.rs:7:5
  |
7 |     *x;
  |     ^^ move occurs because `*x` has type `S`, which does not implement the `Copy` trait

error[E0381]: used binding `ret` isn't initialized
 --> /home/runner/work/glacier/glacier/ices/83539.rs:8:5
  |
6 |     let ret;
  |         --- binding declared here but left uninitialized
7 |     *x;
8 |     ret
  |     ^^^ `ret` used here but it isn't initialized
  |
help: consider assigning a value
  |
6 |     let ret = todo!();
  |             +++++++++

error: aborting due to 2 previous errors; 1 warning emitted

Some errors have detailed explanations: E0381, E0507.
For more information about an error, try `rustc --explain E0381`.
==============