ices/91502.rs: fixed with errors
=== stdout ===
=== stderr ===
error[E0308]: mismatched types
 --> /home/runner/work/glacier/glacier/ices/91502.rs:2:12
  |
2 |     Ok { ..0 > 0 }
  |            ^^^^^ expected enum `Result`, found `bool`
  |
  = note: expected enum `Result<_, _>`
             found type `bool`

error[E0436]: functional record update syntax requires a struct
 --> /home/runner/work/glacier/glacier/ices/91502.rs:2:12
  |
2 |     Ok { ..0 > 0 }
  |            ^^^^^

error[E0308]: mismatched types
 --> /home/runner/work/glacier/glacier/ices/91502.rs:2:5
  |
1 | fn main() {
  |           - expected `()` because of default return type
2 |     Ok { ..0 > 0 }
  |     ^^^^^^^^^^^^^^ expected `()`, found enum `Result`
  |
  = note: expected unit type `()`
                  found enum `Result<_, _>`

error: aborting due to 3 previous errors

Some errors have detailed explanations: E0308, E0436.
For more information about an error, try `rustc --explain E0308`.
==============