ices/59191.sh: fixed with errors
=== stdout ===
=== stderr ===
error[E0658]: non-builtin inner attributes are unstable
 --> <anon>:1:1
  |
1 | #![no_main::no_main]
  | ^^^^^^^^^^^^^^^^^^^^
  |
  = note: for more information, see https://github.com/rust-lang/rust/issues/54726
  = help: add `#![feature(custom_inner_attributes)]` to the crate attributes to enable

error[E0468]: an `extern crate` loading macros must be at the crate root

error: expected crate top-level item to be a module after macro expansion, found a function
 --> <anon>:1:1
  |
1 | #![no_main::no_main]
  | ^^^^^^^^^^^^^^^^^^^^

error[E0433]: failed to resolve: maybe a missing crate `std`?

error[E0601]: `main` function not found in crate `rust_out`
 --> <anon>:1:1
  |
1 | #![no_main::no_main]
  | ^^^^^^^^^^^^^^^^^^^^ consider adding a `main` function at the crate level

error: aborting due to 5 previous errors

Some errors have detailed explanations: E0433, E0468, E0601, E0658.
For more information about an error, try `rustc --explain E0433`.
==============