ices/113017.rs: fixed with errors
=== stdout ===
=== stderr ===
error: expected one of `:`, `@`, or `|`, found `)`
 --> /home/runner/work/glacier/glacier/ices/113017.rs:3:22
  |
3 | pub fn String<V>(elem)
  |                      ^ expected one of `:`, `@`, or `|`
  |
  = note: anonymous parameters are removed in the 2018 edition (see RFC 1685)
help: if this is a `self` type, give it a parameter name
  |
3 | pub fn String<V>(self: elem)
  |                  +++++
help: if this is a parameter name, give it a type
  |
3 | pub fn String<V>(elem: TypeName)
  |                      ++++++++++
help: if this is a type, explicitly ignore the parameter name
  |
3 | pub fn String<V>(_: elem)
  |                  ++

error[E0261]: use of undeclared lifetime name `'a`
 --> /home/runner/work/glacier/glacier/ices/113017.rs:5:8
  |
5 |     V: 'a,
  |        ^^ undeclared lifetime
  |
  = note: for more information on higher-ranked polymorphism, visit https://doc.rust-lang.org/nomicon/hrtb.html
help: consider making the bound lifetime-generic with a new `'a` lifetime
  |
5 |     for<'a> V: 'a,
  |     +++++++
help: consider introducing lifetime `'a` here
  |
3 | pub fn String<'a, V>(elem)
  |               +++

error[E0261]: use of undeclared lifetime name `'a`
 --> /home/runner/work/glacier/glacier/ices/113017.rs:6:39
  |
6 |     for<const N: usize = { || {}}> V: 'a, 
  |                                       ^^ undeclared lifetime
  |
help: consider making the bound lifetime-generic with a new `'a` lifetime
  |
6 |     for<'a, const N: usize = { || {}}> V: 'a, 
  |         +++
help: consider introducing lifetime `'a` here
  |
3 | pub fn String<'a, V>(elem)
  |               +++

error[E0637]: `&` without an explicit lifetime name cannot be used here
 --> /home/runner/work/glacier/glacier/ices/113017.rs:7:26
  |
7 |     for<C2: , R2, R3: > <&str as IntoIterator>::Item: 'static,
  |                          ^ explicit lifetime name needed here
  |
help: consider introducing a higher-ranked lifetime here
  |
7 |     for<'a> for<C2: , R2, R3: > <&'a str as IntoIterator>::Item: 'static,
  |     +++++++                       ++

error[E0658]: only lifetime parameters can be used in this context
 --> /home/runner/work/glacier/glacier/ices/113017.rs:6:15
  |
6 |     for<const N: usize = { || {}}> V: 'a, 
  |               ^
  |
  = note: see issue #108185 <https://github.com/rust-lang/rust/issues/108185> for more information
  = help: add `#![feature(non_lifetime_binders)]` to the crate attributes to enable

error[E0658]: only lifetime parameters can be used in this context
 --> /home/runner/work/glacier/glacier/ices/113017.rs:7:9
  |
7 |     for<C2: , R2, R3: > <&str as IntoIterator>::Item: 'static,
  |         ^^    ^^  ^^
  |
  = note: see issue #108185 <https://github.com/rust-lang/rust/issues/108185> for more information
  = help: add `#![feature(non_lifetime_binders)]` to the crate attributes to enable

warning: the feature `generic_const_exprs` is incomplete and may not be safe to use and/or cause compiler crashes
 --> /home/runner/work/glacier/glacier/ices/113017.rs:1:12
  |
1 | #![feature(generic_const_exprs)]
  |            ^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #76560 <https://github.com/rust-lang/rust/issues/76560> for more information
  = note: `#[warn(incomplete_features)]` on by default

error: defaults for generic parameters are not allowed in `for<...>` binders
 --> /home/runner/work/glacier/glacier/ices/113017.rs:6:9
  |
6 |     for<const N: usize = { || {}}> V: 'a, 
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0601]: `main` function not found in crate `113017`
 --> /home/runner/work/glacier/glacier/ices/113017.rs:8:3
  |
8 | {}
  |   ^ consider adding a `main` function to `/home/runner/work/glacier/glacier/ices/113017.rs`

error[E0277]: `&str` is not an iterator
 --> /home/runner/work/glacier/glacier/ices/113017.rs:3:1
  |
3 | / pub fn String<V>(elem)
4 | | where
5 | |     V: 'a,
6 | |     for<const N: usize = { || {}}> V: 'a, 
7 | |     for<C2: , R2, R3: > <&str as IntoIterator>::Item: 'static,
  | |______________________________________________________________^ `&str` is not an iterator; try calling `.chars()` or `.bytes()`
  |
  = help: the trait `Iterator` is not implemented for `&str`
  = note: required for `&str` to implement `IntoIterator`

error[E0277]: `&str` is not an iterator
 --> /home/runner/work/glacier/glacier/ices/113017.rs:3:8
  |
3 | pub fn String<V>(elem)
  |        ^^^^^^ `&str` is not an iterator; try calling `.chars()` or `.bytes()`
  |
  = help: the trait `Iterator` is not implemented for `&str`
  = note: required for `&str` to implement `IntoIterator`

error: aborting due to 10 previous errors; 1 warning emitted

Some errors have detailed explanations: E0261, E0277, E0601, E0637, E0658.
For more information about an error, try `rustc --explain E0261`.
==============