ices/71611.rs: fixed with errors
=== stdout ===
=== stderr ===
error[E0557]: feature has been removed
 --> /home/runner/work/glacier/glacier/ices/71611.rs:2:12
  |
2 | #![feature(const_compare_raw_pointers)]
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^ feature has been removed
  |
  = note: cannot be allowed in const eval in any meaningful way

warning: the feature `const_generics` is incomplete and may not be safe to use and/or cause compiler crashes
 --> /home/runner/work/glacier/glacier/ices/71611.rs:1:12
  |
1 | #![feature(const_generics)]
  |            ^^^^^^^^^^^^^^
  |
  = note: `#[warn(incomplete_features)]` on by default
  = note: see issue #44580 <https://github.com/rust-lang/rust/issues/44580> for more information

error: using function pointers as const generic parameters is forbidden
 --> /home/runner/work/glacier/glacier/ices/71611.rs:4:21
  |
4 | fn func<A, const F: fn(inner: A)>(outer: A) {
  |                     ^^^^^^^^^^^^

error: aborting due to 2 previous errors; 1 warning emitted

For more information about this error, try `rustc --explain E0557`.
==============