ices/66500.rs: fixed with errors
=== stdout ===
=== stderr ===
error[E0507]: cannot move out of `*u.x` which is behind a shared reference
 --> /home/runner/work/glacier/glacier/ices/66500.rs:6:14
  |
6 |     unsafe { *u.x }
  |              ^^^^ move occurs because `*u.x` has type `std::string::String`, which does not implement the `Copy` trait

error: aborting due to previous error

For more information about this error, try `rustc --explain E0507`.
==============