ices/102173.rs: fixed with errors
=== stdout ===
=== stderr ===
error[E0277]: `[i32; 4]` needs to be a pointer-sized type
 --> /home/runner/work/glacier/glacier/ices/102173.rs:7:13
  |
7 |     let i = [1, 2, 3, 4] as dyn* Debug;
  |             ^^^^^^^^^^^^ `[i32; 4]` needs to be a pointer-sized type
  |
  = help: the trait `PointerSized` is not implemented for `[i32; 4]`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
==============