ices/104631.rs: fixed with errors
=== stdout ===
=== stderr ===
warning: the feature `dyn_star` is incomplete and may not be safe to use and/or cause compiler crashes
 --> /home/runner/work/glacier/glacier/ices/104631.rs:3:12
  |
3 | #![feature(dyn_star)]
  |            ^^^^^^^^
  |
  = note: see issue #102425 <https://github.com/rust-lang/rust/issues/102425> for more information
  = note: `#[warn(incomplete_features)]` on by default

error[E0277]: `AlignedUsize` needs to have the same ABI as a pointer
  --> /home/runner/work/glacier/glacier/ices/104631.rs:14:13
   |
14 |     let x = AlignedUsize(12) as dyn* Debug;
   |             ^^^^^^^^^^^^^^^^ `AlignedUsize` needs to be a pointer-like type
   |
   = help: the trait `PointerLike` is not implemented for `AlignedUsize`

error: aborting due to previous error; 1 warning emitted

For more information about this error, try `rustc --explain E0277`.
==============