ices/81712.rs: fixed with errors
=== stdout ===
=== stderr ===
warning: the feature `generic_associated_types` is incomplete and may not be safe to use and/or cause compiler crashes
 --> /home/runner/work/glacier/glacier/ices/81712.rs:1:12
  |
1 | #![feature(generic_associated_types)]
  |            ^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(incomplete_features)]` on by default
  = note: see issue #44265 <https://github.com/rust-lang/rust/issues/44265> for more information

error[E0601]: `main` function not found in crate `81712`
  --> /home/runner/work/glacier/glacier/ices/81712.rs:1:1
   |
1  | / #![feature(generic_associated_types)]
2  | |
3  | | // The cyclic dependency between trait A and B compiles as expected
4  | | trait A {
...  |
17 | |     type CType: C<DType = Self>;
18 | | }
   | |_^ consider adding a `main` function to `/home/runner/work/glacier/glacier/ices/81712.rs`

error[E0107]: missing generics for associated type `C::DType`
  --> /home/runner/work/glacier/glacier/ices/81712.rs:14:10
   |
14 |     type DType<T>: D<T, CType = Self>;
   |          ^^^^^ expected 1 type argument
   |
note: associated type defined here, with 1 type parameter: `T`
  --> /home/runner/work/glacier/glacier/ices/81712.rs:14:10
   |
14 |     type DType<T>: D<T, CType = Self>;
   |          ^^^^^ -
help: use angle brackets to add missing type argument
   |
14 |     type DType<T><T>: D<T, CType = Self>;
   |               ^^^

error: aborting due to 2 previous errors; 1 warning emitted

Some errors have detailed explanations: E0107, E0601.
For more information about an error, try `rustc --explain E0107`.
==============