ices/71169.rs: fixed with errors
=== stdout ===
=== stderr ===
error[E0770]: the type of const parameters must not depend on other generic parameters
 --> /home/runner/work/glacier/glacier/ices/71169.rs:4:43
  |
4 | fn foo<const LEN: usize, const DATA: [u8; LEN]>() {}
  |                                           ^^^ the type must not depend on the parameter `LEN`

error: constant expression depends on a generic parameter
 --> /home/runner/work/glacier/glacier/ices/71169.rs:8:14
  |
8 |     foo::<4, DATA>();
  |              ^^^^
  |
  = note: this may fail depending on what value the parameter takes

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0770`.
==============