ices/109071.rs: fixed with errors
=== stdout ===
=== stderr ===
error[E0637]: `&` without an explicit lifetime name cannot be used here
 --> /home/runner/work/glacier/glacier/ices/109071.rs:4:17
  |
4 |     type Item = &[T];
  |                 ^ explicit lifetime name needed here

error[E0601]: `main` function not found in crate `109071`
  --> /home/runner/work/glacier/glacier/ices/109071.rs:11:2
   |
11 | }
   |  ^ consider adding a `main` function to `/home/runner/work/glacier/glacier/ices/109071.rs`

error[E0107]: missing generics for struct `Windows`
 --> /home/runner/work/glacier/glacier/ices/109071.rs:3:9
  |
3 | impl<T> Windows {
  |         ^^^^^^^ expected 1 generic argument
  |
note: struct defined here, with 1 generic parameter: `T`
 --> /home/runner/work/glacier/glacier/ices/109071.rs:1:8
  |
1 | struct Windows<T> {}
  |        ^^^^^^^ -
help: add missing generic argument
  |
3 | impl<T> Windows<T> {
  |                +++

error[E0658]: inherent associated types are unstable
 --> /home/runner/work/glacier/glacier/ices/109071.rs:4:5
  |
4 |     type Item = &[T];
  |     ^^^^^^^^^^^^^^^^^
  |
  = note: see issue #8995 <https://github.com/rust-lang/rust/issues/8995> for more information
  = help: add `#![feature(inherent_associated_types)]` to the crate attributes to enable

error: aborting due to 4 previous errors

Some errors have detailed explanations: E0107, E0601, E0637, E0658.
For more information about an error, try `rustc --explain E0107`.
==============