ices/83765.rs: fixed with errors
=== stdout ===
=== stderr ===
error[E0557]: feature has been removed
 --> /home/runner/work/glacier/glacier/ices/83765.rs:1:12
  |
1 | #![feature(const_generics, const_evaluatable_checked)]
  |            ^^^^^^^^^^^^^^ feature has been removed
  |
  = note: removed in favor of `#![feature(adt_const_params]` and `#![feature(generic_const_exprs)]`

error[E0557]: feature has been removed
 --> /home/runner/work/glacier/glacier/ices/83765.rs:1:28
  |
1 | #![feature(const_generics, const_evaluatable_checked)]
  |                            ^^^^^^^^^^^^^^^^^^^^^^^^^ feature has been removed
  |
  = note: renamed to `generic_const_exprs`

error: generic parameters may not be used in const operations
  --> /home/runner/work/glacier/glacier/ices/83765.rs:12:31
   |
12 |     fn size(&self) -> [usize; Self::DIM];
   |                               ^^^^^^^^^ cannot perform const operation using `Self`
   |
   = note: type parameters may not be used in const expressions
   = help: use `#![feature(generic_const_exprs)]` to allow generic const expressions

error: generic parameters may not be used in const operations
  --> /home/runner/work/glacier/glacier/ices/83765.rs:13:39
   |
13 |     fn inbounds(&self, index: [usize; Self::DIM]) -> bool {
   |                                       ^^^^^^^^^ cannot perform const operation using `Self`
   |
   = note: type parameters may not be used in const expressions
   = help: use `#![feature(generic_const_exprs)]` to allow generic const expressions

error: generic parameters may not be used in const operations
  --> /home/runner/work/glacier/glacier/ices/83765.rs:20:35
   |
20 |     fn bget(&self, index: [usize; Self::DIM]) -> Option<Self::Element>;
   |                                   ^^^^^^^^^ cannot perform const operation using `Self`
   |
   = note: type parameters may not be used in const expressions
   = help: use `#![feature(generic_const_exprs)]` to allow generic const expressions

error: generic parameters may not be used in const operations
  --> /home/runner/work/glacier/glacier/ices/83765.rs:24:28
   |
24 |     ) -> LazyUpdim<Self, { Self::DIM }, NEWDIM> {
   |                            ^^^^^^^^^ cannot perform const operation using `Self`
   |
   = note: type parameters may not be used in const expressions
   = help: use `#![feature(generic_const_exprs)]` to allow generic const expressions

error: generic parameters may not be used in const operations
  --> /home/runner/work/glacier/glacier/ices/83765.rs:34:80
   |
34 |     fn bmap<T, F: Fn(Self::Element) -> T>(&self, foo: F) -> BMap<T, Self, F, { Self::DIM }> {
   |                                                                                ^^^^^^^^^ cannot perform const operation using `Self`
   |
   = note: type parameters may not be used in const expressions
   = help: use `#![feature(generic_const_exprs)]` to allow generic const expressions

error: generic parameters may not be used in const operations
  --> /home/runner/work/glacier/glacier/ices/83765.rs:47:85
   |
47 | impl<'a, T: Broadcastable, const DIM: usize> TensorDimension for LazyUpdim<'a, T, { T::DIM }, DIM> {
   |                                                                                     ^^^^^^ cannot perform const operation using `T`
   |
   = note: type parameters may not be used in const expressions
   = help: use `#![feature(generic_const_exprs)]` to allow generic const expressions

error: generic parameters may not be used in const operations
  --> /home/runner/work/glacier/glacier/ices/83765.rs:50:80
   |
50 | impl<'a, T: Broadcastable, const DIM: usize> TensorSize for LazyUpdim<'a, T, { T::DIM }, DIM> {
   |                                                                                ^^^^^^ cannot perform const operation using `T`
   |
   = note: type parameters may not be used in const expressions
   = help: use `#![feature(generic_const_exprs)]` to allow generic const expressions

error: generic parameters may not be used in const operations
  --> /home/runner/work/glacier/glacier/ices/83765.rs:55:83
   |
55 | impl<'a, T: Broadcastable, const DIM: usize> Broadcastable for LazyUpdim<'a, T, { T::DIM }, DIM> {
   |                                                                                   ^^^^^^ cannot perform const operation using `T`
   |
   = note: type parameters may not be used in const expressions
   = help: use `#![feature(generic_const_exprs)]` to allow generic const expressions

error: generic parameters may not be used in const operations
  --> /home/runner/work/glacier/glacier/ices/83765.rs:63:31
   |
63 |         let newindex: [usize; T::DIM] = Default::default(); //array_init::array_init(|i| if size[i] > 1 {index[i]} else {0});
   |                               ^^^^^^ cannot perform const operation using `T`
   |
   = note: type parameters may not be used in const expressions
   = help: use `#![feature(generic_const_exprs)]` to allow generic const expressions

error[E0277]: the trait bound `&Self: Broadcastable` is not satisfied
  --> /home/runner/work/glacier/glacier/ices/83765.rs:29:9
   |
29 |         LazyUpdim {
   |         ^^^^^^^^^ the trait `Broadcastable` is not implemented for `&Self`
   |
note: required by `LazyUpdim`
  --> /home/runner/work/glacier/glacier/ices/83765.rs:42:1
   |
42 | struct LazyUpdim<'a, T: Broadcastable, const OLDDIM: usize, const DIM: usize> {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 12 previous errors

Some errors have detailed explanations: E0277, E0557.
For more information about an error, try `rustc --explain E0277`.
==============