ices/109191.rs: fixed with errors
=== stdout ===
=== stderr ===
error: missing `for` in a trait impl
 --> /home/runner/work/glacier/glacier/ices/109191.rs:5:11
  |
5 | impl Foo<> () {
  |           ^ help: add `for` here

error[E0107]: trait takes 1 generic argument but 0 generic arguments were supplied
 --> /home/runner/work/glacier/glacier/ices/109191.rs:5:6
  |
5 | impl Foo<> () {
  |      ^^^ expected 1 generic argument
  |
note: trait defined here, with 1 generic parameter: `T`
 --> /home/runner/work/glacier/glacier/ices/109191.rs:1:7
  |
1 | trait Foo<T>: {
  |       ^^^ -
help: add missing generic argument
  |
5 | impl Foo<T> () {
  |          +

error[E0121]: the placeholder `_` is not allowed within types on item signatures for functions
 --> /home/runner/work/glacier/glacier/ices/109191.rs:6:16
  |
6 |     fn bar( s: _) -> _ {}
  |                ^     ^ not allowed in type signatures
  |                |
  |                not allowed in type signatures
  |
help: use type parameters instead
  |
6 |     fn bar<T>( s: T) -> _ {}
  |           +++     ~
help: try replacing `_` with the type in the corresponding trait method signature
  |
6 |     fn bar( s: _) -> ((),) {}
  |                      ~~~~~

error: aborting due to 3 previous errors

Some errors have detailed explanations: E0107, E0121.
For more information about an error, try `rustc --explain E0107`.
==============