ices/83836.rs: fixed with errors (#718)
=== stdout ===
=== stderr ===
error[E0601]: `main` function not found in crate `83836`
 --> /home/runner/work/glacier/glacier/ices/83836.rs:1:1
  |
1 | fn func2(_x: Option<Target = Option>) {}
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ consider adding a `main` function to `/home/runner/work/glacier/glacier/ices/83836.rs`

error[E0107]: missing generics for enum `Option`
   --> /home/runner/work/glacier/glacier/ices/83836.rs:1:14
    |
1   | fn func2(_x: Option<Target = Option>) {}
    |              ^^^^^^ expected 1 type argument
    |
note: enum defined here, with 1 type parameter: `T`
help: use angle brackets to add missing type argument
    |
1   | fn func2(_x: Option<T><Target = Option>) {}
    |                    ^^^

error[E0107]: missing generics for enum `Option`
   --> /home/runner/work/glacier/glacier/ices/83836.rs:1:30
    |
1   | fn func2(_x: Option<Target = Option>) {}
    |                              ^^^^^^ expected 1 type argument
    |
note: enum defined here, with 1 type parameter: `T`
help: use angle brackets to add missing type argument
    |
1   | fn func2(_x: Option<Target = Option<T>>) {}
    |                                    ^^^

error[E0229]: associated type bindings are not allowed here
 --> /home/runner/work/glacier/glacier/ices/83836.rs:1:21
  |
1 | fn func2(_x: Option<Target = Option>) {}
  |                     ^^^^^^^^^^^^^^^ associated type not allowed here

error: aborting due to 4 previous errors

Some errors have detailed explanations: E0107, E0229, E0601.
For more information about an error, try `rustc --explain E0107`.
==============

Co-authored-by: rustbot <rustbot@users.noreply.github.com>