ices/86238.rs: fixed with errors (#866)
=== stdout ===
=== stderr ===
error[E0658]: language items are subject to change
 --> /home/runner/work/glacier/glacier/ices/86238.rs:6:1
  |
6 | #[lang = "sized"]
  | ^^^^^^^^^^^^^^^^^
  |
  = help: add `#![feature(lang_items)]` to the crate attributes to enable

error[E0658]: language items are subject to change
 --> /home/runner/work/glacier/glacier/ices/86238.rs:8:1
  |
8 | #[lang = "copy"]
  | ^^^^^^^^^^^^^^^^
  |
  = help: add `#![feature(lang_items)]` to the crate attributes to enable

error[E0658]: the `#[no_core]` attribute is an experimental feature
 --> /home/runner/work/glacier/glacier/ices/86238.rs:1:1
  |
1 | #![no_core]
  | ^^^^^^^^^^^
  |
  = note: see issue #29639 <https://github.com/rust-lang/rust/issues/29639> for more information
  = help: add `#![feature(no_core)]` to the crate attributes to enable

error: failed to find an overloaded call trait for closure call
 --> /home/runner/work/glacier/glacier/ices/86238.rs:4:5
  |
4 |     one()
  |     ^^^^^
  |
  = help: make sure the `fn`/`fn_mut`/`fn_once` lang items are defined and have associated `call`/`call_mut`/`call_once` functions

error: aborting due to 4 previous errors

For more information about this error, try `rustc --explain E0658`.
==============

Co-authored-by: rustbot <rustbot@users.noreply.github.com>