ices/80433.rs: fixed with errors
=== stdout ===
=== stderr ===
error[E0107]: missing generics for associated type `TestMut::Output`
 --> /home/runner/work/glacier/glacier/ices/80433.rs:7:10
  |
7 |     type Output<'a>;
  |          ^^^^^^ expected 1 lifetime argument
  |
note: associated type defined here, with 1 lifetime parameter: `'a`
 --> /home/runner/work/glacier/glacier/ices/80433.rs:7:10
  |
7 |     type Output<'a>;
  |          ^^^^^^ --
help: use angle brackets to add missing lifetime argument
  |
7 |     type Output<'a><'a>;
  |                ^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0107`.
==============