ices/77320.rs: fixed with errors
=== stdout ===
=== stderr ===
error[E0133]: call to unsafe function is unsafe and requires unsafe function or block
 --> /home/runner/work/glacier/glacier/ices/77320.rs:2:18
  |
2 | const ZST: &() = std::mem::transmute(FOO);
  |                  ^^^^^^^^^^^^^^^^^^^^^^^^ call to unsafe function
  |
  = note: consult the function's documentation for information on how to avoid undefined behavior

error: aborting due to previous error

For more information about this error, try `rustc --explain E0133`.
==============