ices/83309.rs: fixed with errors (#736)
=== stdout ===
=== stderr ===
error[E0594]: cannot assign to `*v` which is behind a `&` reference
 --> /home/runner/work/glacier/glacier/ices/83309.rs:3:9
  |
2 |     for v in Query.iter_mut() {
  |              ---------------- this iterator yields `&` references
3 |         *v -= 1;
  |         ^^^^^^^ `v` is a `&` reference, so the data it refers to cannot be written

error: aborting due to previous error

For more information about this error, try `rustc --explain E0594`.
==============

Co-authored-by: rustbot <rustbot@users.noreply.github.com>