ices/105742.sh: fixed with errors
=== stdout ===
=== stderr ===
error[E0107]: missing generics for associated type `SVec::Item`
 --> out.rs:7:35
  |
7 | trait SVec: Index<<Self as SVec>::Item, Output = <Index<<Self as SVec>::Item, Output = <Self as SVec>::Item> as SVec>::Item> {
  |                                   ^^^^ expected 1 lifetime argument
  |
note: associated type defined here, with 1 lifetime parameter: `'a`
 --> out.rs:8:10
  |
8 |     type Item<'a, T>;
  |          ^^^^ --
help: add missing lifetime argument
  |
7 | trait SVec: Index<<Self as SVec>::Item<'a>, Output = <Index<<Self as SVec>::Item, Output = <Self as SVec>::Item> as SVec>::Item> {
  |                                   ~~~~~~~~

error[E0107]: missing generics for associated type `SVec::Item`
 --> out.rs:7:35
  |
7 | trait SVec: Index<<Self as SVec>::Item, Output = <Index<<Self as SVec>::Item, Output = <Self as SVec>::Item> as SVec>::Item> {
  |                                   ^^^^ expected 1 generic argument
  |
note: associated type defined here, with 1 generic parameter: `T`
 --> out.rs:8:10
  |
8 |     type Item<'a, T>;
  |          ^^^^     -
help: add missing generic argument
  |
7 | trait SVec: Index<<Self as SVec>::Item<T>, Output = <Index<<Self as SVec>::Item, Output = <Self as SVec>::Item> as SVec>::Item> {
  |                                   ~~~~~~~

error[E0107]: missing generics for associated type `SVec::Item`
 --> out.rs:7:73
  |
7 | trait SVec: Index<<Self as SVec>::Item, Output = <Index<<Self as SVec>::Item, Output = <Self as SVec>::Item> as SVec>::Item> {
  |                                                                         ^^^^ expected 1 lifetime argument
  |
note: associated type defined here, with 1 lifetime parameter: `'a`
 --> out.rs:8:10
  |
8 |     type Item<'a, T>;
  |          ^^^^ --
help: add missing lifetime argument
  |
7 | trait SVec: Index<<Self as SVec>::Item, Output = <Index<<Self as SVec>::Item<'a>, Output = <Self as SVec>::Item> as SVec>::Item> {
  |                                                                         ~~~~~~~~

error[E0107]: missing generics for associated type `SVec::Item`
 --> out.rs:7:73
  |
7 | trait SVec: Index<<Self as SVec>::Item, Output = <Index<<Self as SVec>::Item, Output = <Self as SVec>::Item> as SVec>::Item> {
  |                                                                         ^^^^ expected 1 generic argument
  |
note: associated type defined here, with 1 generic parameter: `T`
 --> out.rs:8:10
  |
8 |     type Item<'a, T>;
  |          ^^^^     -
help: add missing generic argument
  |
7 | trait SVec: Index<<Self as SVec>::Item, Output = <Index<<Self as SVec>::Item<T>, Output = <Self as SVec>::Item> as SVec>::Item> {
  |                                                                         ~~~~~~~

error[E0107]: missing generics for associated type `SVec::Item`
 --> out.rs:7:104
  |
7 | trait SVec: Index<<Self as SVec>::Item, Output = <Index<<Self as SVec>::Item, Output = <Self as SVec>::Item> as SVec>::Item> {
  |                                                                                                        ^^^^ expected 1 lifetime argument
  |
note: associated type defined here, with 1 lifetime parameter: `'a`
 --> out.rs:8:10
  |
8 |     type Item<'a, T>;
  |          ^^^^ --
help: add missing lifetime argument
  |
7 | trait SVec: Index<<Self as SVec>::Item, Output = <Index<<Self as SVec>::Item, Output = <Self as SVec>::Item<'a>> as SVec>::Item> {
  |                                                                                                        ~~~~~~~~

error[E0107]: missing generics for associated type `SVec::Item`
 --> out.rs:7:104
  |
7 | trait SVec: Index<<Self as SVec>::Item, Output = <Index<<Self as SVec>::Item, Output = <Self as SVec>::Item> as SVec>::Item> {
  |                                                                                                        ^^^^ expected 1 generic argument
  |
note: associated type defined here, with 1 generic parameter: `T`
 --> out.rs:8:10
  |
8 |     type Item<'a, T>;
  |          ^^^^     -
help: add missing generic argument
  |
7 | trait SVec: Index<<Self as SVec>::Item, Output = <Index<<Self as SVec>::Item, Output = <Self as SVec>::Item<T>> as SVec>::Item> {
  |                                                                                                        ~~~~~~~

error[E0107]: missing generics for associated type `SVec::Item`
 --> out.rs:7:120
  |
7 | trait SVec: Index<<Self as SVec>::Item, Output = <Index<<Self as SVec>::Item, Output = <Self as SVec>::Item> as SVec>::Item> {
  |                                                                                                                        ^^^^ expected 1 lifetime argument
  |
note: associated type defined here, with 1 lifetime parameter: `'a`
 --> out.rs:8:10
  |
8 |     type Item<'a, T>;
  |          ^^^^ --
help: add missing lifetime argument
  |
7 | trait SVec: Index<<Self as SVec>::Item, Output = <Index<<Self as SVec>::Item, Output = <Self as SVec>::Item> as SVec>::Item<'a>> {
  |                                                                                                                        ~~~~~~~~

error[E0107]: missing generics for associated type `SVec::Item`
 --> out.rs:7:120
  |
7 | trait SVec: Index<<Self as SVec>::Item, Output = <Index<<Self as SVec>::Item, Output = <Self as SVec>::Item> as SVec>::Item> {
  |                                                                                                                        ^^^^ expected 1 generic argument
  |
note: associated type defined here, with 1 generic parameter: `T`
 --> out.rs:8:10
  |
8 |     type Item<'a, T>;
  |          ^^^^     -
help: add missing generic argument
  |
7 | trait SVec: Index<<Self as SVec>::Item, Output = <Index<<Self as SVec>::Item, Output = <Self as SVec>::Item> as SVec>::Item<T>> {
  |                                                                                                                        ~~~~~~~

error[E0107]: missing generics for associated type `SVec::Item`
  --> out.rs:10:38
   |
10 |     fn len(&self) -> <Self as SVec>::Item;
   |                                      ^^^^ expected 1 lifetime argument
   |
note: associated type defined here, with 1 lifetime parameter: `'a`
  --> out.rs:8:10
   |
8  |     type Item<'a, T>;
   |          ^^^^ --
help: add missing lifetime argument
   |
10 |     fn len(&self) -> <Self as SVec>::Item<'_>;
   |                                      ~~~~~~~~

error[E0107]: missing generics for associated type `SVec::Item`
  --> out.rs:10:38
   |
10 |     fn len(&self) -> <Self as SVec>::Item;
   |                                      ^^^^ expected 1 generic argument
   |
note: associated type defined here, with 1 generic parameter: `T`
  --> out.rs:8:10
   |
8  |     type Item<'a, T>;
   |          ^^^^     -
help: add missing generic argument
   |
10 |     fn len(&self) -> <Self as SVec>::Item<T>;
   |                                      ~~~~~~~

error: aborting due to 10 previous errors

For more information about this error, try `rustc --explain E0107`.
==============