ices/93835.rs: fixed with errors
=== stdout ===
=== stderr ===
error: comparison operators cannot be chained
 --> /home/runner/work/glacier/glacier/ices/93835.rs:2:8
  |
1 | fn e() {
  |        - while parsing this struct
2 |     p:a<p:p<e=6>>
  |        ^        ^
  |
  = help: use `::<...>` instead of `<...>` to specify lifetime, type, or const arguments
  = help: or use `(...)` if you meant to specify fn arguments

error[E0425]: cannot find value `p` in this scope
 --> /home/runner/work/glacier/glacier/ices/93835.rs:2:5
  |
2 |     p:a<p:p<e=6>>
  |     ^ not found in this scope
  |
help: you might have meant to write a `struct` literal
  |
1 ~ fn e() { SomeStruct {
2 |     p:a<p:p<e=6>>
3 ~ }}
  |
help: maybe you meant to write a path separator here
  |
2 |     p::a<p:p<e=6>>
  |      ~~
help: maybe you meant to write an assignment here
  |
2 |     let p:a<p:p<e=6>>
  |     ~~~~~

error[E0658]: associated const equality is incomplete
 --> /home/runner/work/glacier/glacier/ices/93835.rs:2:13
  |
2 |     p:a<p:p<e=6>>
  |             ^^^
  |
  = note: see issue #92827 <https://github.com/rust-lang/rust/issues/92827> for more information
  = help: add `#![feature(associated_const_equality)]` to the crate attributes to enable

error[E0658]: associated type bounds are unstable
 --> /home/runner/work/glacier/glacier/ices/93835.rs:2:9
  |
2 |     p:a<p:p<e=6>>
  |         ^^^^^^^^
  |
  = note: see issue #52662 <https://github.com/rust-lang/rust/issues/52662> for more information
  = help: add `#![feature(associated_type_bounds)]` to the crate attributes to enable

error[E0601]: `main` function not found in crate `93835`
 --> /home/runner/work/glacier/glacier/ices/93835.rs:1:1
  |
1 | / fn e() {
2 | |     p:a<p:p<e=6>>
3 | | }
  | |_^ consider adding a `main` function to `/home/runner/work/glacier/glacier/ices/93835.rs`

error: aborting due to 5 previous errors

Some errors have detailed explanations: E0425, E0601, E0658.
For more information about an error, try `rustc --explain E0425`.
==============