ices/112574.rs: fixed with errors
=== stdout ===
=== stderr ===
error[E0412]: cannot find type `V` in this scope
 --> /home/runner/work/glacier/glacier/ices/112574.rs:7:4
  |
7 | }> V: IntoIterator
  |    ^ not found in this scope
  |
help: you might be missing a type parameter
  |
3 | pub fn bar<V>()
  |           +++

warning: the feature `non_lifetime_binders` is incomplete and may not be safe to use and/or cause compiler crashes
 --> /home/runner/work/glacier/glacier/ices/112574.rs:1:12
  |
1 | #![feature(non_lifetime_binders)]
  |            ^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #108185 <https://github.com/rust-lang/rust/issues/108185> for more information
  = note: `#[warn(incomplete_features)]` on by default

error: aborting due to previous error; 1 warning emitted

For more information about this error, try `rustc --explain E0412`.
==============