ices/83288.rs: fixed with errors
=== stdout ===
=== stderr ===
error[E0557]: feature has been removed
 --> /home/runner/work/glacier/glacier/ices/83288.rs:2:12
  |
2 | #![feature(const_generics, const_evaluatable_checked)]
  |            ^^^^^^^^^^^^^^ feature has been removed
  |
  = note: removed in favor of `#![feature(adt_const_params]` and `#![feature(generic_const_exprs)]`

error[E0557]: feature has been removed
 --> /home/runner/work/glacier/glacier/ices/83288.rs:2:28
  |
2 | #![feature(const_generics, const_evaluatable_checked)]
  |                            ^^^^^^^^^^^^^^^^^^^^^^^^^ feature has been removed
  |
  = note: renamed to `generic_const_exprs`

error: generic parameters may not be used in const operations
  --> /home/runner/work/glacier/glacier/ices/83288.rs:43:10
   |
43 |     [u8; I::NUM_ELEMS]: Sized,
   |          ^^^^^^^^^^^^ cannot perform const operation using `I`
   |
   = note: type parameters may not be used in const expressions
   = help: use `#![feature(generic_const_exprs)]` to allow generic const expressions

error: generic parameters may not be used in const operations
  --> /home/runner/work/glacier/glacier/ices/83288.rs:45:20
   |
45 |     pub data: [u8; I::NUM_ELEMS],
   |                    ^^^^^^^^^^^^ cannot perform const operation using `I`
   |
   = note: type parameters may not be used in const expressions
   = help: use `#![feature(generic_const_exprs)]` to allow generic const expressions

error: generic parameters may not be used in const operations
  --> /home/runner/work/glacier/glacier/ices/83288.rs:53:10
   |
53 |     [u8; I::NUM_ELEMS]: Sized,
   |          ^^^^^^^^^^^^ cannot perform const operation using `I`
   |
   = note: type parameters may not be used in const expressions
   = help: use `#![feature(generic_const_exprs)]` to allow generic const expressions

error: generic parameters may not be used in const operations
  --> /home/runner/work/glacier/glacier/ices/83288.rs:54:10
   |
54 |     [u8; J::NUM_ELEMS]: Sized,
   |          ^^^^^^^^^^^^ cannot perform const operation using `J`
   |
   = note: type parameters may not be used in const expressions
   = help: use `#![feature(generic_const_exprs)]` to allow generic const expressions

error: generic parameters may not be used in const operations
  --> /home/runner/work/glacier/glacier/ices/83288.rs:55:11
   |
55 |     [u8; <I as Concat<J>>::Output::NUM_ELEMS]: Sized,
   |           ^ cannot perform const operation using `I`
   |
   = note: type parameters may not be used in const expressions
   = help: use `#![feature(generic_const_exprs)]` to allow generic const expressions

error: generic parameters may not be used in const operations
  --> /home/runner/work/glacier/glacier/ices/83288.rs:55:23
   |
55 |     [u8; <I as Concat<J>>::Output::NUM_ELEMS]: Sized,
   |                       ^ cannot perform const operation using `J`
   |
   = note: type parameters may not be used in const expressions
   = help: use `#![feature(generic_const_exprs)]` to allow generic const expressions

error[E0601]: `main` function not found in crate `83288`
  --> /home/runner/work/glacier/glacier/ices/83288.rs:1:1
   |
1  | / #![allow(incomplete_features)]
2  | | #![feature(const_generics, const_evaluatable_checked)]
3  | |
4  | | use std::{marker::PhantomData, ops::Mul};
...  |
64 | |     }
65 | | }
   | |_^ consider adding a `main` function to `/home/runner/work/glacier/glacier/ices/83288.rs`

error: constant expression depends on a generic parameter
  --> /home/runner/work/glacier/glacier/ices/83288.rs:61:25
   |
61 |             data: [0u8; <I as Concat<J>>::Output::NUM_ELEMS],
   |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this may fail depending on what value the parameter takes

error: aborting due to 10 previous errors

Some errors have detailed explanations: E0557, E0601.
For more information about an error, try `rustc --explain E0557`.
==============