ices/84020.sh: fixed with errors
=== stdout ===
=== stderr ===
error[E0557]: feature has been removed
 --> <anon>:1:12
  |
1 | #![feature(const_generics, platform_intrinsics, repr_simd)]
  |            ^^^^^^^^^^^^^^ feature has been removed
  |
  = note: removed in favor of `#![feature(adt_const_params]` and `#![feature(generic_const_exprs)]`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0557`.
==============