ices/112824.rs: fixed with errors
=== stdout ===
=== stderr ===
error[E0261]: use of undeclared lifetime name `'a`
 --> /home/runner/work/glacier/glacier/ices/112824.rs:3:21
  |
3 | pub struct Opcode2(&'a S);
  |                   - ^^ undeclared lifetime
  |                   |
  |                   help: consider introducing lifetime `'a` here: `<'a>`

error[E0412]: cannot find type `S` in this scope
 --> /home/runner/work/glacier/glacier/ices/112824.rs:3:24
  |
3 | pub struct Opcode2(&'a S);
  |                        ^ not found in this scope
  |
help: you might be missing a type parameter
  |
3 | pub struct Opcode2<S>(&'a S);
  |                   +++

error: constant pattern depends on a generic parameter
  --> /home/runner/work/glacier/glacier/ices/112824.rs:11:9
   |
11 |         Opcode2::OP2 => unimplemented!(),
   |         ^^^^^^^^^^^^

warning: unused variable: `i`
  --> /home/runner/work/glacier/glacier/ices/112824.rs:10:11
   |
10 |     move |i| match msg_type {
   |           ^ help: if this is intentional, prefix it with an underscore: `_i`
   |
   = note: `#[warn(unused_variables)]` on by default

error: aborting due to 3 previous errors; 1 warning emitted

Some errors have detailed explanations: E0261, E0412.
For more information about an error, try `rustc --explain E0261`.
==============