ices/85350.rs: fixed with errors
=== stdout ===
=== stderr ===
error: lifetime in trait object type must be followed by `+`
 --> /home/runner/work/glacier/glacier/ices/85350.rs:1:26
  |
1 | impl FnMut(&Context) for 'tcx {
  |                          ^^^^

error[E0407]: method `print` is not a member of trait `FnMut`
 --> /home/runner/work/glacier/glacier/ices/85350.rs:2:5
  |
2 |     fn print () -> Self :: Output{ }
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not a member of trait `FnMut`

error[E0412]: cannot find type `Context` in this scope
 --> /home/runner/work/glacier/glacier/ices/85350.rs:1:13
  |
1 | impl FnMut(&Context) for 'tcx {
  |             ^^^^^^^ not found in this scope
  |
help: consider importing one of these items
  |
1 | use core::task::Context;
  |
1 | use std::task::Context;
  |

warning: trait objects without an explicit `dyn` are deprecated
 --> /home/runner/work/glacier/glacier/ices/85350.rs:1:26
  |
1 | impl FnMut(&Context) for 'tcx {
  |                          ^^^^ help: use `dyn`: `dyn 'tcx`
  |
  = note: `#[warn(bare_trait_objects)]` on by default
  = warning: this is accepted in the current edition (Rust 2018) but is a hard error in Rust 2021!
  = note: for more information, see issue #80165 <https://github.com/rust-lang/rust/issues/80165>

error[E0601]: `main` function not found in crate `85350`
 --> /home/runner/work/glacier/glacier/ices/85350.rs:1:1
  |
1 | / impl FnMut(&Context) for 'tcx {
2 | |     fn print () -> Self :: Output{ }
3 | | }
  | |_^ consider adding a `main` function to `/home/runner/work/glacier/glacier/ices/85350.rs`

error[E0224]: at least one trait is required for an object type
 --> /home/runner/work/glacier/glacier/ices/85350.rs:1:26
  |
1 | impl FnMut(&Context) for 'tcx {
  |                          ^^^^

error[E0261]: use of undeclared lifetime name `'tcx`
 --> /home/runner/work/glacier/glacier/ices/85350.rs:1:26
  |
1 | impl FnMut(&Context) for 'tcx {
  |     -                    ^^^^ undeclared lifetime
  |     |
  |     help: consider introducing lifetime `'tcx` here: `<'tcx>`
  |
  = help: if you want to experiment with in-band lifetime bindings, add `#![feature(in_band_lifetimes)]` to the crate attributes

error[E0229]: associated type bindings are not allowed here
 --> /home/runner/work/glacier/glacier/ices/85350.rs:1:6
  |
1 | impl FnMut(&Context) for 'tcx {
  |      ^^^^^^^^^^^^^^^ associated type not allowed here

error[E0212]: cannot use the associated type of a trait with uninferred generic parameters
 --> /home/runner/work/glacier/glacier/ices/85350.rs:2:20
  |
2 |     fn print () -> Self :: Output{ }
  |                    ^^^^^^^^^^^^^^ help: use a fully qualified path with inferred lifetimes: `<[type error] as FnOnce<(&[type error],)>>::Output`

error: aborting due to 8 previous errors; 1 warning emitted

Some errors have detailed explanations: E0212, E0224, E0229, E0261, E0407, E0412, E0601.
For more information about an error, try `rustc --explain E0212`.
==============