ices/71382.rs: fixed with errors
=== stdout ===
=== stderr ===
error[E0557]: feature has been removed
 --> /home/runner/work/glacier/glacier/ices/71382.rs:1:28
  |
1 | #![feature(const_generics, const_compare_raw_pointers)]
  |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^ feature has been removed
  |
  = note: cannot be allowed in const eval in any meaningful way

error: using function pointers as const generic parameters is forbidden
  --> /home/runner/work/glacier/glacier/ices/71382.rs:15:23
   |
15 |     fn test<const FN: fn()>(&self) {
   |                       ^^^^

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0557`.
==============