ices/87258.rs: fixed with errors
=== stdout ===
=== stderr ===
error[E0557]: feature has been removed
 --> /home/runner/work/glacier/glacier/ices/87258.rs:1:12
  |
1 | #![feature(min_type_alias_impl_trait)]
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^ feature has been removed
  |
  = note: removed in favor of full type_alias_impl_trait

error[E0658]: `impl Trait` in type aliases is unstable
  --> /home/runner/work/glacier/glacier/ices/87258.rs:27:30
   |
27 |     type FooFuture<'a, 'b> = impl Future<Output = Result<(), Self::Error>>;
   |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #63063 <https://github.com/rust-lang/rust/issues/63063> for more information
   = help: add `#![feature(type_alias_impl_trait)]` to the crate attributes to enable

error[E0601]: `main` function not found in crate `87258`
  --> /home/runner/work/glacier/glacier/ices/87258.rs:1:1
   |
1  | / #![feature(min_type_alias_impl_trait)]
2  | | #![feature(generic_associated_types)]
3  | | use std::future::Future;
4  | |
...  |
35 | |     }
36 | | }
   | |_^ consider adding a `main` function to `/home/runner/work/glacier/glacier/ices/87258.rs`

error: aborting due to 3 previous errors

Some errors have detailed explanations: E0557, E0601, E0658.
For more information about an error, try `rustc --explain E0557`.
==============