ices/62200.rs: fixed with errors
=== stdout ===
=== stderr ===
error[E0582]: binding for associated type `Output` references an anonymous lifetime, which does not appear in the trait input types
  --> /home/runner/work/glacier/glacier/ices/62200.rs:11:36
   |
11 |     F: FnOnce(<X as Ty<'_>>::V) -> Option<<X as Ty<'_>>::V>
   |                                    ^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: lifetimes appearing in an associated type are not considered constrained

error: aborting due to previous error

For more information about this error, try `rustc --explain E0582`.
==============