ices/97381.rs: fixed with errors
=== stdout ===
=== stderr ===
error[E0505]: cannot move out of `v` because it is borrowed
  --> /home/runner/work/glacier/glacier/ices/97381.rs:33:14
   |
31 |     let el = &v[0];
   |               - borrow of `v` occurs here
32 | 
33 |     for _ in v {
   |              ^ move out of `v` occurs here
34 |         // this triggers bug
35 |         println!("{}", ***el > 0);
   |                         ---- borrow later used here

error: aborting due to previous error

For more information about this error, try `rustc --explain E0505`.
==============