ices/108952.rs: fixed with errors
=== stdout ===
=== stderr ===
error[E0106]: missing lifetime specifier
 --> /home/runner/work/glacier/glacier/ices/108952.rs:6:25
  |
6 | struct UwU<'b, const T: LifetimeGeneric>(&'b ());
  |                         ^^^^^^^^^^^^^^^ expected named lifetime parameter

error[E0741]: `LifetimeGeneric<'_>` must implement `ConstParamTy` to be used as the type of a const generic parameter
 --> /home/runner/work/glacier/glacier/ices/108952.rs:6:25
  |
6 | struct UwU<'b, const T: LifetimeGeneric>(&'b ());
  |                         ^^^^^^^^^^^^^^^
  |
help: add `#[derive(ConstParamTy, PartialEq, Eq)]` to the struct
  |
4 + #[derive(ConstParamTy, PartialEq, Eq)]
5 | struct LifetimeGeneric<'a>(&'a ());
  |

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0106, E0741.
For more information about an error, try `rustc --explain E0106`.
==============