ices/69414.sh: fixed with errors
=== stdout ===
=== stderr ===
/home/runner/work/glacier/glacier/ices/69414.sh: line 3: PartialEq: command not found
/home/runner/work/glacier/glacier/ices/69414.sh: line 3: Eq: command not found
error[E0770]: the type of const parameters must not depend on other generic parameters
 --> <anon>:3:22
  |
3 | struct B<T, const N: T>(PhantomData<[T; N]>); //~ ERROR const generics are unstable
  |                      ^ the type must not depend on the parameter `T`

error[E0658]: const generics are unstable
 --> <anon>:3:19
  |
3 | struct B<T, const N: T>(PhantomData<[T; N]>); //~ ERROR const generics are unstable
  |                   ^
  |
  = note: see issue #44580 <https://github.com/rust-lang/rust/issues/44580> for more information
  = help: add `#![feature(const_generics)]` to the crate attributes to enable

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0658, E0770.
For more information about an error, try `rustc --explain E0658`.
==============