ices/113272.rs: fixed with errors
=== stdout ===
=== stderr ===
error[E0412]: cannot find type `Missing` in this scope
 --> /home/runner/work/glacier/glacier/ices/113272.rs:5:25
  |
5 | impl Trait for () where Missing: Trait {}
  |                         ^^^^^^^ not found in this scope

error: aborting due to previous error

For more information about this error, try `rustc --explain E0412`.
==============