ices/73727.rs: fixed with errors
=== stdout ===
=== stderr ===
error[E0557]: feature has been removed
 --> /home/runner/work/glacier/glacier/ices/73727.rs:1:12
  |
1 | #![feature(const_generics)]
  |            ^^^^^^^^^^^^^^ feature has been removed
  |
  = note: removed in favor of `#![feature(adt_const_params]` and `#![feature(generic_const_exprs)]`

error: `&'static [u32]` is forbidden as the type of a const generic parameter
 --> /home/runner/work/glacier/glacier/ices/73727.rs:4:15
  |
4 | fn a<const X: &'static [u32]>() {}
  |               ^^^^^^^^^^^^^^
  |
  = note: the only supported types are integers, `bool` and `char`
  = help: more complex types are supported with `#![feature(adt_const_params)]`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0557`.
==============