ices/84737.sh: fixed with errors
=== stdout ===
=== stderr ===
error[E0557]: feature has been removed
 --> <anon>:2:12
  |
2 | #![feature(const_generics)]
  |            ^^^^^^^^^^^^^^ feature has been removed
  |
  = note: removed in favor of `#![feature(adt_const_params]` and `#![feature(generic_const_exprs)]`

warning: unnecessary braces around const expression
 --> <anon>:5:26
  |
5 | async fn test(test: [(); { 0 }]) {
  |                          ^^^^^ help: remove these braces
  |
  = note: `#[warn(unused_braces)]` on by default

error: aborting due to previous error; 1 warning emitted

For more information about this error, try `rustc --explain E0557`.
==============