ices/54840.rs: fixed with errors
=== stdout ===
=== stderr ===
error[E0557]: feature has been removed
 --> /home/runner/work/glacier/glacier/ices/54840.rs:1:12
  |
1 | #![feature(impl_trait_in_bindings)]
  |            ^^^^^^^^^^^^^^^^^^^^^^ feature has been removed
  |
  = note: the implementation was not maintainable, the feature may get reintroduced once the current refactorings are done

error[E0562]: `impl Trait` not allowed outside of function and method return types
 --> /home/runner/work/glacier/glacier/ices/54840.rs:7:13
  |
7 |     let j: &impl Add = &i;
  |             ^^^^^^^^

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0557, E0562.
For more information about an error, try `rustc --explain E0557`.
==============