ices/62879.rs: fixed with errors
=== stdout ===
=== stderr ===
error[E0770]: the type of const parameters must not depend on other generic parameters
 --> /home/runner/work/glacier/glacier/ices/62879.rs:3:38
  |
3 | fn foo<const N: usize, const A: [u8; N]>() {}
  |                                      ^ the type must not depend on the parameter `N`

warning: the feature `const_generics` is incomplete and may not be safe to use and/or cause compiler crashes
 --> /home/runner/work/glacier/glacier/ices/62879.rs:1:12
  |
1 | #![feature(const_generics)]
  |            ^^^^^^^^^^^^^^
  |
  = note: `#[warn(incomplete_features)]` on by default
  = note: see issue #44580 <https://github.com/rust-lang/rust/issues/44580> for more information

error: constant expression depends on a generic parameter
 --> /home/runner/work/glacier/glacier/ices/62879.rs:6:14
  |
6 |     foo::<1, {[1]}>();
  |              ^^^^^
  |
  = note: this may fail depending on what value the parameter takes

error: aborting due to 2 previous errors; 1 warning emitted

For more information about this error, try `rustc --explain E0770`.
==============