ices/93282.rs: fixed with errors
=== stdout ===
=== stderr ===
error: expected one of `.`, `:`, `;`, `?`, `for`, `loop`, `while`, `{`, `}`, or an operator, found `,`
 --> /home/runner/work/glacier/glacier/ices/93282.rs:2:7
  |
2 |   A<'a,>
  |       ^ expected one of 10 possible tokens
  |
help: use `::<...>` instead of `<...>` to specify lifetime, type, or const arguments
  |
2 |   A::<'a,>
  |    ++

error: aborting due to previous error

==============