ices/70303.rs: fixed with errors
=== stdout ===
=== stderr ===
error[E0107]: missing generics for associated type `Document::Cursor`
 --> /home/runner/work/glacier/glacier/ices/70303.rs:6:10
  |
6 |     type Cursor<'a>: DocCursor<'a>;
  |          ^^^^^^ expected 1 lifetime argument
  |
note: associated type defined here, with 1 lifetime parameter: `'a`
 --> /home/runner/work/glacier/glacier/ices/70303.rs:6:10
  |
6 |     type Cursor<'a>: DocCursor<'a>;
  |          ^^^^^^ --
help: use angle brackets to add missing lifetime argument
  |
6 |     type Cursor<'a><'a>: DocCursor<'a>;
  |                ^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0107`.
==============