ices/101465.rs: fixed with errors
=== stdout ===
=== stderr ===
error[E0308]: `match` arms have incompatible types
  --> /home/runner/work/glacier/glacier/ices/101465.rs:16:18
   |
14 | /     match true {
15 | |         true => B,
   | |                 - this is found to be of type `B`
16 | |         false => C,
   | |                  ^ expected struct `B`, found struct `C`
17 | |     }
   | |_____- `match` arms have incompatible types
   |
help: you could change the return type to be a boxed trait object
   |
11 | fn foo() -> Box<dyn Sized> {
   |             ~~~~~~~      +
help: if you change the return type to expect trait objects, box the returned expressions
   |
15 ~         true => Box::new(B),
16 ~         false => Box::new(C),
   |

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
==============